export const SOCKET_EVENTS = {
  NEW_CHAT: "NEW_CHAT",
  SYSTEM_NOTICE: "SYSTEM_NOTICE",
  ROOM_LIST_UPDATED: "ROOM_LIST_UPDATED",
  ROOM_CREATED: "ROOM_CREATED",
  JOIN_SUCCESS: "JOIN_SUCCESS",
} as const;